import { Property } from './types';

export const properties: Property[] = [
  {
    id: 'prop-1',
    title: 'Modern 1 Bed Apartment',
    address: '123 Thika Road',
    price: 25000,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 750,
    available: true,
    image: 'https://unsplash.com/photos/modern-luxury-living-interior-3d-rendering-concept-qe0Tu9mVs7U',
    description: 'Modern apartment with great amenities in a prime location. Features include tiled floors, modern kitchen, and secure parking.',
    landlord: {
      name: 'John Doe 1',
      phone: '+254 712 345 678',
      email: 'landlord1@example.com',
    },
    location: {
      lat: -1.1450,
      lng: 36.9550,
    },
  },
  {
    id: 'prop-2',
    title: 'Modern 2 Bed Apartment',
    address: '456 Kamiti Road',
    price: 40000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 900,
    available: false,
    image: 'https://unsplash.com/photos/dining-table-set-placed-beside-glass-window-tleCJiDOri0',
    description: 'Modern apartment with great amenities in a prime location. Features include tiled floors, modern kitchen, and secure parking.',
    landlord: {
      name: 'John Doe 2',
      phone: '+254 712 345 678',
      email: 'landlord2@example.com',
    },
    location: {
      lat: -1.1550,
      lng: 36.9650,
    },
  },
  {
    id: 'prop-3',
    title: 'Modern 1 Bed Apartment',
    address: '789 Bypass Road',
    price: 30000,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 600,
    available: true,
    image: 'https://unsplash.com/photos/a-living-room-filled-with-furniture-and-a-fire-place-s-ZJpt0UdpU',
    description: 'Modern apartment with great amenities in a prime location. Features include tiled floors, modern kitchen, and secure parking.',
    landlord: {
      name: 'John Doe 3',
      phone: '+254 712 345 678',
      email: 'landlord3@example.com',
    },
    location: {
      lat: -1.1400,
      lng: 36.9600,
    },
  },
  {
    id: 'prop-4',
    title: 'Modern 2 Bed Apartment',
    address: '321 Matangi Road',
    price: 45000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1000,
    available: true,
    image: 'https://unsplash.com/photos/a-living-room-with-a-couch-a-table-and-chairs-E_J7HhGttHM',
    description: 'Modern apartment with great amenities in a prime location. Features include tiled floors, modern kitchen, and secure parking.',
    landlord: {
      name: 'John Doe 4',
      phone: '+254 712 345 678',
      email: 'landlord4@example.com',
    },
    location: {
      lat: -1.1500,
      lng: 36.9500,
    },
  },
  {
    id: 'prop-5',
    title: 'Modern 1 Bed Apartment',
    address: '654 Gatongora Road',
    price: 28000,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 700,
    available: false,
    image: 'https://unsplash.com/photos/brown-staircase-UV81E0oXXWQ',
    description: 'Modern apartment with great amenities in a prime location. Features include tiled floors, modern kitchen, and secure parking.',
    landlord: {
      name: 'John Doe 5',
      phone: '+254 712 345 678',
      email: 'landlord5@example.com',
    },
    location: {
      lat: -1.1600,
      lng: 36.9700,
    },
  },
  {
    id: 'prop-6',
    title: 'Modern 2 Bed Apartment',
    address: '987 Thika Road',
    price: 42000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 950,
    available: true,
    image: 'https://unsplash.com/photos/a-living-room-filled-with-furniture-and-a-large-window-OtXADkUh3-I',
    description: 'Modern apartment with great amenities in a prime location. Features include tiled floors, modern kitchen, and secure parking.',
    landlord: {
      name: 'John Doe 6',
      phone: '+254 712 345 678',
      email: 'landlord6@example.com',
    },
    location: {
      lat: -1.1450,
      lng: 36.9650,
    },
  },
  {
    id: 'prop-7',
    title: 'Modern 1 Bed Apartment',
    address: '111 Kamiti Road',
    price: 26000,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 650,
    available: true,
    image: 'https://unsplash.com/photos/brown-wooden-table-and-chairs-NFbwes_e-jI',
    description: 'Modern apartment with great amenities in a prime location. Features include tiled floors, modern kitchen, and secure parking.',
    landlord: {
      name: 'John Doe 7',
      phone: '+254 712 345 678',
      email: 'landlord7@example.com',
    },
    location: {
      lat: -1.1550,
      lng: 36.9550,
    },
  },
  {
    id: 'prop-8',
    title: 'Modern 2 Bed Apartment',
    address: '222 Bypass Road',
    price: 47000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1100,
    available: false,
    image: 'https://unsplash.com/photos/white-and-brown-wooden-table-and-chairs-OlFHzNjg9kY',
    description: 'Modern apartment with great amenities in a prime location. Features include tiled floors, modern kitchen, and secure parking.',
    landlord: {
      name: 'John Doe 8',
      phone: '+254 712 345 678',
      email: 'landlord8@example.com',
    },
    location: {
      lat: -1.1400,
      lng: 36.9700,
    },
  },
  {
    id: 'prop-9',
    title: 'Modern 1 Bed Apartment',
    address: '333 Matangi Road',
    price: 29000,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 800,
    available: true,
    image: 'https://unsplash.com/photos/a-living-room-with-a-couch-chair-table-and-potted-plant-v4SuNLE0OnI',
    description: 'Modern apartment with great amenities in a prime location. Features include tiled floors, modern kitchen, and secure parking.',
    landlord: {
      name: 'John Doe 9',
      phone: '+254 712 345 678',
      email: 'landlord9@example.com',
    },
    location: {
      lat: -1.1500,
      lng: 36.9600,
    },
  },
  {
    id: 'prop-10',
    title: 'Modern 2 Bed Apartment',
    address: '444 Gatongora Road',
    price: 43000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1050,
    available: true,
    image: 'https://unsplash.com/photos/black-and-white-wall-mounted-painting-PyeXkOVmG1Y',
    description: 'Modern apartment with great amenities in a prime location. Features include tiled floors, modern kitchen, and secure parking.',
    landlord: {
      name: 'John Doe 10',
      phone: '+254 712 345 678',
      email: 'landlord10@example.com',
    },
    location: {
      lat: -1.1450,
      lng: 36.9550,
    },
  },
  {
    id: 'prop-11',
    title: 'Modern 1 Bed Apartment',
    address: '555 Thika Road',
    price: 27000,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 720,
    available: false,
    image: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NjJ8fGludGVyaW9yJTIwZGVzaWdufGVufDB8fDB8fHww',
    description: 'Modern apartment with great amenities in a prime location. Features include tiled floors, modern kitchen, and secure parking.',
    landlord: {
      name: 'John Doe 11',
      phone: '+254 712 345 678',
      email: 'landlord11@example.com',
    },
    location: {
      lat: -1.1550,
      lng: 36.9650,
    },
  },
  {
    id: 'prop-12',
    title: 'Modern 2 Bed Apartment',
    address: '666 Kamiti Road',
    price: 48000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1150,
    available: true,
    image: 'https://images.unsplash.com/photo-1600607686527-6fb886090705?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Njd8fGludGVyaW9yJTIwZGVzaWdufGVufDB8fDB8fHww',
    description: 'Modern apartment with great amenities in a prime location. Features include tiled floors, modern kitchen, and secure parking.',
    landlord: {
      name: 'John Doe 12',
      phone: '+254 712 345 678',
      email: 'landlord12@example.com',
    },
    location: {
      lat: -1.1400,
      lng: 36.9600,
    },
  },
  {
    id: 'prop-13',
    title: 'Modern 1 Bed Apartment',
    address: '777 Bypass Road',
    price: 31000,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 680,
    available: true,
    image: 'https://unsplash.com/photos/white-and-brown-living-room-set-KJUGhE9ojro',
    description: 'Modern apartment with great amenities in a prime location. Features include tiled floors, modern kitchen, and secure parking.',
    landlord: {
      name: 'John Doe 13',
      phone: '+254 712 345 678',
      email: 'landlord13@example.com',
    },
    location: {
      lat: -1.1500,
      lng: 36.9500,
    },
  },
  {
    id: 'prop-14',
    title: 'Modern 2 Bed Apartment',
    address: '888 Matangi Road',
    price: 44000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 980,
    available: false,
    image: 'https://unsplash.com/photos/living-room-with-green-plants-and-brown-wooden-floor-8e679XbGGy4',
    description: 'Modern apartment with great amenities in a prime location. Features include tiled floors, modern kitchen, and secure parking.',
    landlord: {
      name: 'John Doe 14',
      phone: '+254 712 345 678',
      email: 'landlord14@example.com',
    },
    location: {
      lat: -1.1600,
      lng: 36.9700,
    },
  },
  {
    id: 'prop-15',
    title: 'Modern 1 Bed Apartment',
    address: '999 Gatongora Road',
    price: 32000,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 730,
    available: true,
    image: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8aG91c2V8ZW58MHx8MHx8fDA%3D',
    description: 'Modern apartment with great amenities in a prime location. Features include tiled floors, modern kitchen, and secure parking.',
    landlord: {
      name: 'John Doe 15',
      phone: '+254 712 345 678',
      email: 'landlord15@example.com',
    },
    location: {
      lat: -1.1450,
      lng: 36.9650,
    },
  },
];
